# SITE CONFIGURATION
baseurl:
url: "https://blog.rockarch.org"
permalink: /:title

# THEME-SPECIFIC CONFIGURATION
theme_settings:
  # Meta
  title: Bits & Bytes
  subtitle: The Rockefeller Archive Center Blog
  description: "News from Rockefeller Archive Center's Staff" # used by search engines

  # Localization strings
  str_next_page: "Next"
  str_previous_page: "Prev"
  str_continue_reading: "Continue reading"

# PAGINATION
paginate: 5
paginate_path: "blog/page:num"

# BUILD SETTINGS
markdown: kramdown
highlighter: rouge
sass:
  sass_dir: _sass
  style: compressed
plugins:
  - jekyll-paginate
  - jekyll-redirect-from
